# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kermit}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Machado Fernández"]
  s.date = %q{2012-08-07}
  s.default_executable = %q{kermit}
  s.description = %q{Allows to retrieve info from diferent Data Streams for data mining purpouses}
  s.email = %q{daniel.machado.fernandez@gmail.com}
  s.executables = ["kermit"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/kermit",
    "config/config.example.yml",
    "doc/Adapter.html",
    "doc/Converter.html",
    "doc/DAO.html",
    "doc/KermitPFC.html",
    "doc/Link.html",
    "doc/Logging.html",
    "doc/RandomAdapter.html",
    "doc/RandomConverter.html",
    "doc/RandomPhraseGenerator.html",
    "doc/ToUser.html",
    "doc/TwitterAdapter.html",
    "doc/TwitterConverter.html",
    "doc/USMF.html",
    "doc/User.html",
    "doc/WebSocketClient.html",
    "doc/WebSocketServer.html",
    "doc/_index.html",
    "doc/class_list.html",
    "doc/css/common.css",
    "doc/css/full_list.css",
    "doc/css/style.css",
    "doc/file.LICENSE.html",
    "doc/file.README.html",
    "doc/file_list.html",
    "doc/frames.html",
    "doc/index.html",
    "doc/js/app.js",
    "doc/js/full_list.js",
    "doc/js/jquery.js",
    "doc/method_list.html",
    "doc/top-level-namespace.html",
    "lib/business/adapter/adapter.rb",
    "lib/business/adapter/random_adapter.rb",
    "lib/business/adapter/twitter_adapter.rb",
    "lib/business/converter/converter.rb",
    "lib/business/converter/random_converter.rb",
    "lib/business/converter/twitter_converter.rb",
    "lib/business/random_phrase_generator.rb",
    "lib/helper/DAO.rb",
    "lib/helper/websocket_client.rb",
    "lib/helper/websocket_server.rb",
    "lib/kermitpfc.rb",
    "lib/logging.rb",
    "lib/model/USMF/USMF.rb",
    "lib/model/USMF/link.rb",
    "lib/model/USMF/to_user.rb",
    "lib/model/USMF/user.rb",
    "lib/model/templates/USMF",
    "lib/model/templates/atom.xml",
    "lib/model/templates/example",
    "lib/model/templates/rss.xml",
    "lib/model/templates/template",
    "lib/model/templates/tweet",
    "spec/DAO_spec.rb",
    "spec/random_adapter_spec.rb",
    "spec/random_converter_spec.rb",
    "spec/random_phrase_generator_spec.rb",
    "spec/twitter_adapter_spec.rb",
    "spec/twitter_converter_spec.rb",
    "websocket_client.html"
  ]
  s.homepage = %q{http://github.com/danielmachado/kermit}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Allows to retrieve info from diferent Data Streams}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<em-http-request>, ["= 0.2.7"])
      s.add_runtime_dependency(%q<em-websocket>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<twitter-stream>, [">= 0"])
      s.add_runtime_dependency(%q<commander>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<airbrake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<em-http-request>, ["= 0.2.7"])
      s.add_dependency(%q<em-websocket>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<twitter-stream>, [">= 0"])
      s.add_dependency(%q<commander>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<airbrake>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<em-http-request>, ["= 0.2.7"])
    s.add_dependency(%q<em-websocket>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<twitter-stream>, [">= 0"])
    s.add_dependency(%q<commander>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<airbrake>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

