redis:
 db: #Database name where you want to store the statuses
 twitter: #Key under you want to found your tweets
 # you must add keys for your own stream implementations
 host: #address of your Redis-Server 
 port: #port of your Redis-Server
 password: #Redis password
#Websocket address to publish the statuses
websocket:
 host: #address of your websocket server
 port: #port of your websocket server
#for each Stream implementation you must define its specific params.
twitter:
 streams:#number of streams you want 
 path: /1/statuses/filter.json
 track: #Keywords you want Twitter tracks and filter the Stream (one for each stream)
  1: #specific keyword for each twitter stream
  2: #another keyword to track
 login: #Your Twitter username
 pass: #Your Twitter password
 port: #Port, in case you need to specific one.
#RandomPhraseGenerator Stream
rpg: #true / false if you want to enable this stream
#if you want to add more Social Networks/Streams, it can be a good idea to follow the previous Twitter structure.